---
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: juice-shop
  namespace: airlock-gateway
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
    custom: {}
