---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-juice-shop
  namespace: juice-shop
spec:
  gatewayClassName: airlock-microgateway
  listeners:
  - name: http
    port: 8080
    hostname: "juice-shop-127-0-0-1.nip.io"
    protocol: HTTP

#    allowedRoutes:
#      namespaces:
#        from: All
