apiVersion: microgateway.airlock.com/v1alpha1
kind: GatewayParameters
metadata:
  name: gatewayparameter-juice-shop
  namespace: juice-shop
spec:
  logging:
    level: info
  kubernetes:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
    deployment:
      replicas: 1
      placement: {}
      engineContainer: {}
      automountServiceAccountToken: false
