---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: juice-shop
spec:
  parentRefs:
    - name: juice-shop-gateway
  hostnames:
    - "juice-shop-127-0-0-1.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: juice-shop
          port: 3000
