---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: juice-shop
  namespace: juice-shop
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-juice-shop
  #hostnames:
  #- "juice-shop-127-0-0-1.nip.io"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: juice-shop
      namespace: juice-shop
      port: 3000

#  - matches:
#    - path:
#        type: PathPrefix
#        value: /
#    backendRefs:
#    - name: juice-shop
#      port: 3000
