---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- contentsecuritypolicy.yaml
- denyrule.yaml
- headerrewrites.yaml
- httproute.yaml
- gateway.yaml
- gatewayparameters.yaml
- referencegrant.yaml
